### ISSUE TITLE
Throw "flatMap is not a function" error when run in Chrome 68 

### ISSUE THREAD

**Issue by wesley-chen** [wesley-chen/image-picker3#2]
Error in event handler for runtime.onMessage: TypeError: e.images.flatMap is not a function
    at f.<anonymous> (chrome-extension://mabimojldggddajhoaoadcnlfbefeffn/popup/popup.js:12:9508)
    at chrome-extension://mabimojldggddajhoaoadcnlfbefeffn/popup/popup.js:12:4697
    at chrome-extension://mabimojldggddajhoaoadcnlfbefeffn/popup/popup.js:12:5919
    at chrome-extension://mabimojldggddajhoaoadcnlfbefeffn/popup/popup.js:12:5899
    at f._withCommit (chrome-extension://mabimojldggddajhoaoadcnlfbefeffn/popup/popup.js:12:7162)
    at f.commit (chrome-extension://mabimojldggddajhoaoadcnlfbefeffn/popup/popup.js:12:5874)
    at f.commit (chrome-extension://mabimojldggddajhoaoadcnlfbefeffn/popup/popup.js:12:2557)
    at chrome-extension://mabimojldggddajhoaoadcnlfbefeffn/popup/popup.js:1204:17451

**Comment by wesley-chen** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap
